//
//  ParshaCircularYearTests.swift
//  HebcalWatchCoreTests
//
//  What the Torah Portion widget's circular complication shows at noon on
//  every day from Sep 1, 2026 through Aug 31, 2027, in all three languages,
//  for the Diaspora and Israel schedules. The expected output lives in
//  Snapshots/parsha-circular-*.md — a Markdown table that renders on GitHub
//  roughly the way the complication looks, and diffs one line per day.
//

import Foundation
import Hebcal
import Testing
@testable import HebcalWatchCore

extension HebcalWatchCoreTests {
    @Suite struct ParshaCircularYear {
        @Test(arguments: [false, true])
        func fullYear(il: Bool) {
            let report = ParshaCircularYear.report(il: il, from: (2026, 9, 1), through: (2027, 8, 31))
            assertSnapshot(report, named: "parsha-circular-\(il ? "israel" : "diaspora").md")
        }

        static let languages: [(name: String, lang: TranslationLang)] = [
            ("Sephardic", .en), ("Ashkenazi", .ashkenazi), ("Hebrew", .he),
        ]

        static func report(il: Bool, from start: (Int, Int, Int), through end: (Int, Int, Int)) -> String {
            let formatters = languages.map { HebcalFormatter(settings: HebcalSettings(il: il, lang: $0.lang)) }
            let hebrewDates = HebcalFormatter(settings: HebcalSettings(il: il, lang: .en))
            var lines = [
                "# Parsha circular complication — \(il ? "Israel" : "Diaspora") schedule",
                "",
                "Generated by `ParshaCircularYearTests`; noon each day.",
                "Legend: `A<br>B` two stacked lines · **bold** holiday name, large, no icon ·",
                "`Name<br>🎭️` one-line holiday with its emoji below · `**🕎**<br>Day 4️⃣` large emoji above ·",
                "`Name 📜` one-line parsha with the Torah icon below. Shabbat rows are bold.",
                "",
                "| Date | Hebrew date | " + languages.map(\.name).joined(separator: " | ") + " |",
                "|---|---|" + String(repeating: "---|", count: languages.count),
            ]
            var day = noon(start)
            let last = noon(end)
            while day <= last {
                let isShabbat = calendar.component(.weekday, from: day) == 7
                var dateCell = dateFormatter.string(from: day)
                if isShabbat {
                    dateCell = "**\(dateCell)**"
                }
                let hdate = HebcalFormatter.hebrewDate(for: day, calendar: calendar)
                let cells = formatters.map { formatter in
                    render(ParshaCircularLayout(entry: HebcalEntry(date: day, formatter: formatter,
                                                                   calendar: calendar)))
                }
                lines.append("| \(dateCell) | \(hebrewDates.dateString(hdate, showYear: false)) | "
                             + cells.joined(separator: " | ") + " |")
                day = calendar.date(byAdding: .day, value: 1, to: day)!
            }
            return lines.joined(separator: "\n") + "\n"
        }

        static func render(_ layout: ParshaCircularLayout) -> String {
            switch layout {
            case let .twoLines(first, second): return "\(first)<br>\(second)"
            case let .emojiAbove(emoji, text): return "**\(emoji)**<br>\(text)"
            case let .holiday(name): return "**\(name)**"
            case let .holidayWithEmoji(name, emoji): return "\(name)<br>\(emoji)"
            case let .parsha(name): return "\(name) 📜"
            }
        }

        // A fixed time zone keeps the output identical on any machine.
        static let calendar: Calendar = {
            var calendar = Calendar(identifier: .gregorian)
            calendar.timeZone = TimeZone(identifier: "America/New_York")!
            return calendar
        }()

        static let dateFormatter: DateFormatter = {
            let formatter = DateFormatter()
            formatter.calendar = calendar
            formatter.timeZone = calendar.timeZone
            formatter.locale = Locale(identifier: "en_US_POSIX")
            formatter.dateFormat = "EEE yyyy-MM-dd"
            return formatter
        }()

        static func noon(_ ymd: (Int, Int, Int)) -> Date {
            calendar.date(from: DateComponents(year: ymd.0, month: ymd.1, day: ymd.2, hour: 12))!
        }
    }
}
